### ISSUE TITLE
Internal error when a project is not found

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#3]
## The Issue

get project API is failing with internal error when the project is not found. 

## Expected Behavior

It should return 404 status with valid JSON

## How to reproduce

Visit
https://capstone.kaustubh-dev.pipal.in/api/projects/foo

## Traceback

```
Traceback (most recent call last):
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaustubh/capstone/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kaustubh/capstone/capstone/api.py", line 66, in get_or_upsert_project
    return project.get_json()
AttributeError: 'NoneType' object has no attribute 'get_json'
```

**Comment by nikochiko** [comment]
Fixed in https://github.com/pipalacademy/capstone/commit/47a50b400bd6b99379877f2325a613f5034d7f99
